# Allure配置文件
allure.results.directory=reports/allure-results
allure.link.issue.pattern=https://github.com/bruce4520196/ApiTestEz/issues/{}
allure.link.tms.pattern=https://github.com/bruce4520196/ApiTestEz/issues/{}